config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat, notice: 'Flat was created successfully'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, notice: 'Flat was deleted successfully'
  end

  def update
    if @flat.update(flat_params)
    redirect_to @flat, notice: 'Flat was edited successfully'
    else
      render :edit
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
  <%= simple_form_for (flat) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs mb-3">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
    </div>
    <div class="form-actions">
      <%= f.submit class: "btn btn-primary mb-3" %> <%= link_to 'Cancel', flats_path, class:"btn btn-danger mb-3" %>
    </div>
  <% end %>

app/views/flats/edit.html.erb
<div class="container mt-3 bg-white p-5 d-flex justify-content-center">
  <div class="bg-light col-8 p-3">
    <h2>Edit this flat:</h2>
    <div class="display-flex">
      <%= render 'form', flat: @flat %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <h2>All our flats:</h2>
  <h5>Total: <%= @flats.count %> flats</h4>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    <% @flats.each do |flat| %>
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h4 class="card-title"><%= flat.name %></h4>
          <h6 class="card-subtitle mb-2 text-muted"><%= flat.address %></h4>
          <p class="card-text"><%= flat.description %></p>
        </div>
        <div class="card-footer d-flex justify-content-between">
            <div>
              <i class="fas fa-users"></i> <%= flat.number_of_guests %>
            </div>
            <div>
              <i class="fas fa-money-bill-alt"></i> <%= flat.price_per_night %>.00
            </div>
        </div>
          <%= link_to 'Details', flat_path(flat.id), class: "btn btn-info" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-3 bg-white p-5 d-flex justify-content-center">
  <div class="bg-light col-8 p-3">
    <h2>Add a new flat:</h2>
    <div class="display-flex">
      <%= render 'form', flat: @flat %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container d-flex justify-content-between">
  <div class="col-8">

    <div class="bg-light rounded border shadow-sm p-3 mb-3">
      <h1><%= @flat.name %></h1>
      <p><%= @flat.address %></p>
      <%= link_to "Edit", edit_flat_path, class: "btn btn-warning" %>
      <%= link_to "Delete", flat_path(@flat.id), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure you want to delete this flat?' } %>
    </div>

    <div class="bg-light rounded border shadow-sm p-3 mb-3">
      <h4>A bit more about this flat...</h4>
      <p><%= @flat.description %></p>
    </div>

  </div>

  <div class="col-3">
    <div class="bg-light rounded border shadow-sm p-3 mb-3">
      <h4>Book this place!</h4>
      <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">From:</span>
        <input type="date" class="form-control" placeholder="from" aria-label="from" aria-describedby="basic-addon1">
      </div>
      <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">To:</span>
        <input type="date" class="form-control" placeholder="to" aria-label="to" aria-describedby="basic-addon1">
      </div>
      <button type="submit" class="btn btn-success col-12">Submit</button>
    </div>

    <div class="bg-light rounded border shadow-sm p-3 mb-3">
      <h4>Details</h4>
      <p class="mb-0"><i class="fas fa-users"></i> <%= @flat.number_of_guests %> <i class="fas fa-money-bill-alt"></i> <%= @flat.price_per_night %>.00</p>
    </div>

    <div class="bg-light rounded border shadow-sm p-3 mb-3 d-flex justify-content-between">
      <h4 class="mb-0">Share</h4>
      <h4 class="mb-0"><i class="fab fa-facebook-square"></i> <i class="fab fa-twitter-square"></i> <i class="fab fa-pinterest-square"></i> <i class="fas fa-envelope-square"></i></h4>
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to 'Simple AirBNB', flats_path, class: "navbar-brand mb-0 h1" %>
        <%= link_to 'Add flat', new_flat_path, class: "btn btn-outline-light" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>